spring:
  application:
    name: JobSearch
  datasource:
    url: jdbc:h2:./db/test;AUTO_SERVER=TRUE
    username: zloy
    password: qwerty
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: always

server:
  port: 8089
