spring:
  application:
    name: JobSearch
  datasource:
    url: jdbc:h2:./db/job_search;AUTO_SERVER=TRUE
    username: zllloy
    password: qwerty
    driver-class-name: org.h2.Driver
#  sql:
#    init:
#      mode: always

  liquibase:
    change-log: classpath:/db/changelog/master.yaml

server:
  port: 8089


